package catalog

import "math/rand/v2"

// FirstNames contains ~500 diverse first names for deterministic customer generation.
var FirstNames = []string{
	"Aaliyah", "Aaron", "Abby", "Abel", "Abigail", "Abraham", "Ada", "Adam", "Adeline", "Adrian",
	"Adriana", "Aiden", "Ailani", "Aisha", "Akira", "Alana", "Albert", "Alejandro", "Alex", "Alexander",
	"Alexandra", "Alexis", "Ali", "Alice", "Alina", "Aliyah", "Allison", "Alma", "Alon", "Alyssa",
	"Amara", "Amaya", "Amber", "Amelia", "Amina", "Amir", "Amit", "Amy", "Ana", "Anastasia",
	"Andre", "Andrea", "Andrew", "Angel", "Angela", "Angelina", "Anika", "Anita", "Anna", "Annabelle",
	"Anthony", "Antonio", "Anya", "April", "Archer", "Aria", "Ariana", "Ariel", "Arthur", "Arya",
	"Asher", "Ashley", "Athena", "Aubrey", "Audrey", "Aurora", "Austin", "Autumn", "Ava", "Avery",
	"Axel", "Ayaan", "Ayla", "Bailey", "Barbara", "Beatrice", "Beau", "Bella", "Benjamin", "Bennett",
	"Bernard", "Bethany", "Bianca", "Blake", "Bobby", "Bonnie", "Boris", "Bradley", "Brandon", "Brayden",
	"Brenda", "Brian", "Brianna", "Bridget", "Brittany", "Brody", "Brooke", "Brooks", "Bruno", "Bryan",
	"Brynn", "Cadence", "Caleb", "Cameron", "Camila", "Camille", "Cara", "Carl", "Carla", "Carlos",
	"Carmen", "Caroline", "Carson", "Carter", "Casey", "Cassandra", "Catalina", "Catherine", "Cecilia", "Celeste",
	"Celia", "Chad", "Charles", "Charlie", "Charlotte", "Chase", "Chelsea", "Cheryl", "Chloe", "Chris",
	"Christian", "Christina", "Christopher", "Clara", "Claire", "Clark", "Claudia", "Clayton", "Clementine", "Cody",
	"Colby", "Cole", "Colin", "Colton", "Connor", "Cooper", "Cora", "Corinne", "Courtney", "Craig",
	"Crystal", "Curtis", "Cynthia", "Dahlia", "Daisy", "Dakota", "Dallas", "Damian", "Dana", "Daniel",
	"Daniela", "Daphne", "Daria", "Darius", "Darla", "Darren", "David", "Dawn", "Dean", "Deborah",
	"Declan", "Delaney", "Delia", "Delilah", "Dennis", "Derek", "Desiree", "Destiny", "Devon", "Diana",
	"Diego", "Dominic", "Donald", "Donna", "Dorothy", "Douglas", "Drake", "Drew", "Dulce", "Duncan",
	"Dylan", "Easton", "Eden", "Edgar", "Edith", "Eduardo", "Edward", "Edwin", "Eileen", "Elaine",
	"Eleanor", "Elena", "Eli", "Eliana", "Elias", "Elijah", "Elise", "Elizabeth", "Ella", "Ellen",
	"Elliot", "Eloise", "Elsa", "Emerson", "Emery", "Emily", "Emma", "Emmanuel", "Emmett", "Eric",
	"Erica", "Erin", "Ernest", "Esme", "Estelle", "Esther", "Ethan", "Eva", "Evan", "Evangeline",
	"Evelyn", "Everett", "Ezra", "Faith", "Fatima", "Felicity", "Felix", "Fern", "Fernando", "Fiona",
	"Flora", "Florence", "Frances", "Francisco", "Frank", "Freya", "Gabriel", "Gabriella", "Gael", "Garrett",
	"Gary", "Gemma", "Genevieve", "George", "Georgia", "Gerald", "Gideon", "Gina", "Giovanni", "Gloria",
	"Grace", "Graham", "Grant", "Grayson", "Gregory", "Griffin", "Gwen", "Hadley", "Hailey", "Haley",
	"Hannah", "Harley", "Harold", "Harper", "Harrison", "Harvey", "Hazel", "Heather", "Hector", "Heidi",
	"Helen", "Helena", "Henry", "Holly", "Hope", "Hudson", "Hugh", "Hugo", "Hunter", "Ian",
	"Ibrahim", "Ida", "Imani", "Ingrid", "Irene", "Iris", "Isaac", "Isabel", "Isabella", "Isaiah",
	"Isla", "Ivan", "Ivy", "Jack", "Jackson", "Jacob", "Jade", "Jaden", "Jake", "James",
	"Jamie", "Jane", "Janet", "Jasmine", "Jason", "Javier", "Jay", "Jayden", "Jean", "Jeffrey",
	"Jenna", "Jennifer", "Jeremiah", "Jeremy", "Jesse", "Jessica", "Jillian", "Joaquin", "Jocelyn", "Joel",
	"John", "Jonah", "Jonathan", "Jordan", "Jorge", "Jose", "Joseph", "Josephine", "Joshua", "Joy",
	"Juan", "Judith", "Julia", "Julian", "Juliana", "Julie", "Juliet", "June", "Justin", "Kai",
	"Kaia", "Kaitlyn", "Kalani", "Karen", "Karina", "Karl", "Kate", "Katherine", "Kathleen", "Katrina",
	"Kay", "Kayla", "Keegan", "Keith", "Kelly", "Kelsey", "Kendall", "Kennedy", "Kenneth", "Kevin",
	"Khloe", "Kian", "Kimberly", "Kingston", "Kinsley", "Kira", "Knox", "Koda", "Kylie", "Kyra",
	"Lacey", "Laila", "Lana", "Lance", "Landon", "Lara", "Laura", "Lauren", "Lawrence", "Layla",
	"Lea", "Leah", "Lena", "Leo", "Leon", "Leonardo", "Leslie", "Levi", "Liam", "Lila",
	"Liliana", "Lillian", "Lily", "Lincoln", "Linda", "Lisa", "Logan", "Lola", "London", "Lorena",
	"Lorenzo", "Lori", "Louis", "Louisa", "Lucas", "Lucia", "Lucille", "Lucy", "Luis", "Luke",
	"Luna", "Lydia", "Lyla", "Mabel", "Mackenzie", "Maddox", "Madeline", "Madison", "Mae", "Maggie",
	"Maia", "Malcolm", "Malik", "Mara", "Marco", "Marcus", "Margaret", "Maria", "Mariah", "Mariana",
	"Marie", "Marilyn", "Marina", "Mario", "Marion", "Mark", "Marlena", "Marley", "Martha", "Martin",
	"Mary", "Mason", "Mateo", "Matilda", "Matthew", "Maverick", "Max", "Maya", "Megan", "Melanie",
	"Melissa", "Melody", "Mercedes", "Mia", "Michael", "Michelle", "Miguel", "Mila", "Miles", "Millie",
	"Milo", "Mira", "Miranda", "Miriam", "Mitchell", "Mohamed", "Molly", "Monica", "Morgan", "Mya",
	"Nadia", "Naomi", "Natalia", "Natalie", "Nathan", "Nathaniel", "Neil", "Nellie", "Nicholas", "Nicole",
	"Nina", "Noah", "Noel", "Nolan", "Nora", "Nova", "Nyla", "Olive", "Oliver", "Olivia",
}

// LastNames contains ~500 diverse last names for deterministic customer generation.
var LastNames = []string{
	"Abbott", "Acosta", "Adams", "Adler", "Aguilar", "Ahmad", "Ahmed", "Ahn", "Akin", "Alavi",
	"Albers", "Alexander", "Ali", "Allen", "Alonso", "Alvarez", "Amato", "Amin", "Andersen", "Anderson",
	"Andrews", "Anwar", "Archer", "Armstrong", "Arnold", "Ashton", "Atkins", "Austin", "Avila", "Ayala",
	"Bach", "Bailey", "Baker", "Baldwin", "Banks", "Barker", "Barnes", "Barnett", "Barrett", "Barton",
	"Bass", "Bates", "Bauer", "Baxter", "Bean", "Beck", "Bell", "Bennett", "Benson", "Berg",
	"Berger", "Bernard", "Berry", "Bishop", "Black", "Blair", "Blake", "Blanco", "Bloom", "Bolton",
	"Bond", "Booker", "Boone", "Booth", "Bowman", "Boyd", "Brady", "Branch", "Bravo", "Brennan",
	"Bridges", "Briggs", "Brooks", "Brown", "Bruce", "Bryant", "Buck", "Burke", "Burns", "Burton",
	"Bush", "Butler", "Byrd", "Caballero", "Cabrera", "Cain", "Caldwell", "Callahan", "Camacho", "Cameron",
	"Campbell", "Campos", "Cannon", "Cardenas", "Carey", "Carlson", "Carpenter", "Carr", "Carrillo", "Carroll",
	"Carter", "Case", "Casey", "Castillo", "Castro", "Chambers", "Chan", "Chang", "Chapman", "Chase",
	"Chavez", "Chen", "Cheng", "Cherry", "Cho", "Choi", "Christensen", "Chung", "Clark", "Clay",
	"Clayton", "Clements", "Cobb", "Cohen", "Cole", "Coleman", "Collier", "Collins", "Colon", "Combs",
	"Conley", "Connolly", "Conway", "Cook", "Cooper", "Copeland", "Cordova", "Cortez", "Costa", "Cox",
	"Craig", "Crawford", "Cross", "Cruz", "Cunningham", "Curry", "Curtis", "Dahl", "Dale", "Dalton",
	"Daniels", "Dara", "Das", "Davidson", "Davis", "Dawson", "Dean", "Delacruz", "Deleon", "Delgado",
	"Dennis", "Desai", "Dewitt", "Diaz", "Dillon", "Dixon", "Doan", "Dominguez", "Donovan", "Dorsey",
	"Douglas", "Drake", "Duarte", "Duke", "Duncan", "Dunn", "Duong", "Duran", "Durham", "Dyer",
	"Eaton", "Edwards", "Elliott", "Ellis", "Emery", "Erickson", "Espinoza", "Estrada", "Evans", "Everett",
	"Falk", "Farmer", "Farrell", "Feng", "Ferguson", "Fernandez", "Fields", "Figueroa", "Fischer", "Fisher",
	"Fitzgerald", "Fleming", "Fletcher", "Flores", "Floyd", "Flynn", "Foley", "Ford", "Foster", "Fox",
	"Francis", "Franco", "Frank", "Franklin", "Frazier", "Freeman", "French", "Frost", "Fuentes", "Fuller",
	"Gaines", "Gallagher", "Gallegos", "Galvan", "Garcia", "Gardner", "Garrett", "Garrison", "Gates", "George",
	"Gibbs", "Gibson", "Gilbert", "Gill", "Gillespie", "Glass", "Glenn", "Glover", "Gomez", "Gonzalez",
	"Good", "Gordon", "Graham", "Grant", "Graves", "Gray", "Green", "Greene", "Gregory", "Griffin",
	"Grimes", "Gross", "Guerrero", "Gupta", "Guzman", "Hahn", "Hale", "Hall", "Hamilton", "Hammond",
	"Hampton", "Han", "Hancock", "Haney", "Hansen", "Harding", "Hardy", "Harper", "Harrington", "Harris",
	"Harrison", "Hart", "Harvey", "Hawkins", "Hayes", "Haynes", "Henderson", "Hendricks", "Henry", "Herman",
	"Hernandez", "Herrera", "Hess", "Hicks", "Higgins", "Hill", "Ho", "Hobbs", "Hodge", "Hoffman",
	"Holland", "Holmes", "Holt", "Hong", "Hood", "Hooper", "Horton", "Howard", "Howell", "Huang",
	"Hubbard", "Hudson", "Huff", "Hughes", "Hunt", "Hunter", "Hussain", "Hutchinson", "Huynh", "Hyde",
	"Ibrahim", "Ingram", "Irwin", "Islam", "Ivanov", "Jackson", "Jacobs", "Jacobson", "James", "Jarvis",
	"Jefferson", "Jenkins", "Jensen", "Jimenez", "Johnson", "Johnston", "Jones", "Jordan", "Joseph", "Joshi",
	"Juarez", "Jung", "Kaplan", "Kara", "Kaufman", "Kaur", "Keene", "Keith", "Keller", "Kelly",
	"Kemp", "Kennedy", "Kent", "Kerr", "Khan", "Kim", "King", "Kirk", "Klein", "Knight",
	"Knox", "Koch", "Koh", "Kowalski", "Kumar", "Kwon", "Lam", "Lamb", "Lambert", "Lancaster",
	"Lane", "Lang", "Larsen", "Larson", "Lawrence", "Lawson", "Le", "Lee", "Leon", "Leonard",
	"Levy", "Lewis", "Li", "Lim", "Lin", "Lindsey", "Little", "Liu", "Livingston", "Lloyd",
	"Logan", "Long", "Lopez", "Lowe", "Lu", "Lucas", "Luna", "Lund", "Lynch", "Lynn",
	"Lyons", "Ma", "Mack", "Madden", "Maddox", "Mahoney", "Maldonado", "Malik", "Malone", "Manning",
	"Marks", "Marsh", "Marshall", "Martin", "Martinez", "Mason", "Mathews", "Matsumoto", "Maxwell", "May",
	"Mayer", "Maynard", "McBride", "McCarthy", "McCoy", "McDaniel", "McDonald", "McDowell", "McGee", "McKenzie",
	"McLaughlin", "McMahon", "Meadows", "Medina", "Mejia", "Mendez", "Mendoza", "Mercer", "Meyer", "Miles",
	"Miller", "Mills", "Mitchell", "Molina", "Monroe", "Montgomery", "Moody", "Moon", "Moore", "Morales",
	"Moran", "Morgan", "Morris", "Morrison", "Morse", "Morton", "Moss", "Mueller", "Munoz", "Murphy",
	"Murray", "Myers", "Nair", "Nash", "Navarro", "Neal", "Nelson", "Newman", "Newton", "Ng",
	"Nguyen", "Nichols", "Nielsen", "Noble", "Nolan", "Norman", "Norris", "Norton", "Novak", "Nunez",
	"Obrien", "Ochoa", "Odonnell", "Olsen", "Olson", "Orozco", "Ortega", "Ortiz", "Osborne", "Owen",
	"Owens", "Pace", "Pacheco", "Padilla", "Page", "Palmer", "Park", "Parker", "Parks", "Patel",
	"Patrick", "Patterson", "Paul", "Payne", "Pearson", "Pena", "Perez", "Perkins", "Perry", "Peters",
}

// GenerateName produces a "firstname lastname" string using the provided PRNG.
func GenerateName(rng *rand.Rand) string {
	return FirstNames[rng.IntN(len(FirstNames))] + " " + LastNames[rng.IntN(len(LastNames))]
}
